Fix exception when deleting process icon cache
Fixes:

System.IO.IOException: The process cannot access the file 'C:\Users\...\AppData\Roaming\CoreDirector\Cache\3B7F9EDC348EC5027B767B65B3E5D5E5' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at CoreDirector.Models.AppProcess.<ApplyAffinity>b__19_0() in C:\Users\...\source\repos\CoreDirector\CoreDirector\Models\AppProcess.cs:line 88

At the time of deleting icon cache, the file is still being held by IconBitmap, thus leading to an exception.
So properly dispose it beforehand.